### ISSUE TITLE
Send message to person

### ISSUE THREAD

**Issue by andrewlew1s** [holistic-web/portfolio-fabricator#11]
We want to allow the user to send an email from the user's website. We will do this through a 'Contact Modal'.

### How
The user will have an option in a new layout schema to display a contact form that allows messages to the emailed to them from their fabricated website.

This will be configured in the administrative UI and will be stored as a new `website` object.

The form will replace the existing `mailto` links on the website and they will open a modal allowing the user to send an email.

The email will be sent with a firebase cloud function rather than directly the browser.

### To Do:
- [x] add modal to the site (hidden based off state of `website.showEmailForm` config object)
    _PR #12 **deployed**_
- [ ] allow user to configure whether or not the email form is displayed (by modifying `website.showEmailForm`) from admin UI
- [x] firebase cloud functions to send the email when a message is received
   _PR #18 **deployed**_

We'll need to document this system and how to configure it well as it is the most complex thing we'll have added to this project so far!

**Comment by andrewlew1s** [comment]
Update on this:
Attempt pushed to new branch
Modal fine
Tried to use "nodemailer" - Docs: https://nodemailer.com/about/ | Nice man: https://www.youtube.com/watch?v=p4bnK0qy89w
Unfortunately when I npm installed nodemailer, it required me to then " npm install --save dns" which proceeded to break everything.
Maybe we should try something else

**Comment by andrewlew1s** [comment]
There is now a PR

**Comment by Charlielancaster** [comment]
@andrewlew1s @michaelfitzhavey 

If this is being hosted on Google, isn't there a google specific way of doing this? Maybe firebase has some functions that you can use? I think I saw something about sending emails in the firebase console for our project....

**Comment by michaelfitzhavey** [comment]
@Charlielancaster How do you mean? We want any user to be able to enter their details and send an email to the account owner, I think the simplest way to do this will simply to send an email to the registered address (we could allow them to provide an alternative inbox for this further down the line)

**Comment by Charlielancaster** [comment]
@michaelfitzhavey Think I got the wrong end of the stick here and thought you wanted a SMTP type of system ha.... Didn't realise it was a sort of contact form!

**Comment by michaelfitzhavey** [comment]
@Charlielancaster wish I knew enough about smtp to understand what that means 😆

**Comment by michaelfitzhavey** [comment]
Adding the website settings section to the management UI is in progress in #21

**Comment by andrewlew1s** [comment]
As part of the work effort we are adding

**Comment by andrewlew1s** [comment]
woops

**Comment by michaelfitzhavey** [comment]
Closing this as not in progress, added to the roadmap here: 1a287494a34994d8f8def37ac4d4db2c83447ac9
