### ISSUE TITLE
Improve layout of generated forms

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/portfolio-fabricator#13]
In the admin UI the forms are still fairly messy, we could definitely look at the docs more and improve those!

**Comment by Charlielancaster** [comment]
Upon looking into improving the appearance of the form and following the docs, I have run into a potential issue between Buefy and Bootsrap-vue as stated in this stack-overflow answer
- https://stackoverflow.com/questions/53219555/why-does-importing-buefy-to-my-vuejs-project-makes-h1-tag-and-some-bootstrap-e 
as the answer states that some of the global classes used may be the same in both frameworks. 

This potential clash could be the reason for some of the style issues we're having such as 
- Buttons and inputs not lining up (Remove buttons in the education and experience sections) 
- Input headings (Generated by the `title` key in the schema) being center aligned and not left

**Comment by michaelfitzhavey** [comment]
Looks like you solved it there @Charlielancaster. Since this is proving to be a pain let's just use bootrap forms for now, closing this.
