### ISSUE TITLE
Quality of Life improvements

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/portfolio-fabricator#31]
@Charlielancaster thought it would be a good idea to get things oiled up and running in this project again.

![relevant-meme](https://media.giphy.com/media/AxpvyWYDHuIH6/giphy.gif)

## We should

- [x] ensure all documentation is up to scratch
    _PR ready https://github.com/holistic-web/portfolio-fabricator/pull/34_

- [x] add a github action to mark stale issues and pull requests similar to https://github.com/holistic-web/toolbox/blob/master/.github/workflows/detect-stale-activity.yml
    _PR merged #32_

- [x] ensure the websites automatically deploy when changes are pushed to the master branch

- [ ] change schema generator from `vue-json-schema-form` to `formvuelatte`
    _PR in progress #36_

- [x] use a shared layout library to improve the look of this UI. Perhaps by refactoringa holistic-layout from https://github.com/holistic-web/toolbox/tree/master/layout
    _in progress in https://github.com/holistic-web/toolbox/issues/113_

**Comment by fitzhavey** [comment]
@Charlielancaster pretty much ready to go, we just have to decide weather we want to bake formvuelatte into `el-layout` 🇲🇽 or directly into this project 🤔

**Comment by Charlielancaster** [comment]
> @Charlielancaster pretty much ready to go, we just have to decide weather we want to bake formvuelatte into `el-layout` 🇲🇽 or directly into this project 🤔

@michaelfitzhavey I suggest baking it into layout. If, moving forward, we want to use it again we can! It should be designed to take in a schema and then work its magic so it can be used for any website
See https://github.com/holistic-web/el-layout/pull/2
